spring:
  application:
    name: order-api

  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
